name: check
on:
  push:
    # branches:
    #   - master
  pull_request:
  # tags:
  #   - "v*.*.*"
  # schedule:
  #   - cron: "0 8 * * *"  # Every day at 10 am

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          # - Windows
          # - MacOs
        py:
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
    steps:
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v2
      - name: Install tox-gh
        run: python -m pip install tox-gh
      - name: Setup test suite
        run: tox r -vv --notest
      - name: Run test suite
        run: tox r --skip-pkg-install
        env:
          PYTEST_ADDOPTS: "-vv --durations=10"
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Setup python for coverage
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install pytest-cov django==4.1 pytest-django
      - name: Run test suite
        run: pytest src --cov=. --cov-report=term-missing --cov-report=xml --cov-fail-under=100
        env:
          PYTEST_ADDOPTS: "-vv --durations=10"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
